name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Auto-detect correct import path for createApiHandler
        run: |
          PKG_JSON="node_modules/@genkit-ai/next/package.json"
          if grep -q '"\\.\\/server"' "$PKG_JSON"; then
            echo "Using @genkit-ai/next/server import"
            sed -i "s|import { createApiHandler } from '@genkit-ai/next';|import { createApiHandler } from '@genkit-ai/next/server';|" src/app/api/genkit/[...slug]/route.ts
          else
            echo "Using @genkit-ai/next import (default)"
            sed -i "s|import { createApiHandler } from '@genkit-ai/next/server';|import { createApiHandler } from '@genkit-ai/next';|" src/app/api/genkit/[...slug]/route.ts
          fi

      - name: Run build
        run: npm run build
